###Получить корзину
GET /api/basket/getone HTTP/1.1
Host: localhost:2900
Cookie: basketId=1


### добавить в корзину
PUT /api/basket/product/1/append/49 HTTP/1.1
Host: localhost:2900
Cookie: basketId=1

### Удалить из корзины
PUT /api/basket/product/1/remove HTTP/1.1
Host: localhost:2900
Cookie: basketId=5

### увеличить количество
PUT /api/basket/product/1/increment/4 HTTP/1.1
Host: localhost:2900
Cookie: basketId=5

###уменьшить количество
PUT /api/basket/product/1/decremant/2 HTTP/1.1
Host: localhost:2900
Cookie: basketId=5

###очистить корзину
PUT /api/basket/clear HTTP/1.1
Host: localhost:2900
Cookie: basketId=5

