### Список решений +
GET /api/solution/getall HTTP/1.1
Host: localhost:2900

###Получить один решение +
GET  /api/solution/getone/2 HTTP/1.1
Host: localhost:2900

### Создать новый решение +
POST /api/solution/create HTTP/1.1
Host: localhost:2900
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjYxOTI1MzIzLCJleHAiOjE2NjIwMTE3MjN9.CZPuoNPodSgFre-vPqVjIV4zQB1RMX9UHeM0P7-k9Mk
Content-Type: application/json; charset=utf-8

{
    "name": "Первый решение"
}

###Обновить решение +
PUT /api/solution/update/2 HTTP/1.1
Host: localhost:2900
# Authorization: Bearer
Content-Type: application/json; charset=utf-8

{
    "name": "Первый решение (new)"
}

###Удалить решение +
DELETE  /api/solution/delete/2 HTTP/1.1
Host: localhost:2900
# Authorization: Bearer